config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/index'
  get 'pages/search'

  resources :users

  get 'sessions/new'
  post 'sessions/create'
  post 'sessions/delete'
  post 'sessions/search'
  delete 'sessions/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  enum search_regexp:{完全一致検索:1,あいまい検索:2}
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :monster, optional: true
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :histories
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :histories
  has_many :monsters, through: :histories

  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'open-uri'
  require 'nokogiri'

  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    @current_user_name ||= @current_user[:name]
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if !Monster.exists?(id: 1) #

      @outstr_terry = ""
      # テリワンのURLからhtml情報を抽出
      #@html,@charset = search_html(url_terry)
      # 抽出したhtmlをパース(解析)してオブジェクトを作成
      #@result_terry = Nokogiri::HTML.parse(@html, nil, @charset)
      # 解析オブジェクトから必要な情報を抽出
      #get_info_terry(@result_terry)

      register #初回でモンスター情報をDBに登録するためのメソッド

    end

    @monster = Monster.all

  end

  def search
    @monster = []
    if params[:search_status] == "true"
      if !params[:keyword].empty?
        if params[:search_regexp] == "完全一致検索"
          Monster.where('pairs LIKE ?', "%＋#{params[:keyword]}").each {|monster| @monster.push(monster)}
          Monster.where('pairs LIKE ?', "#{params[:keyword]}＋%").each {|monster| @monster.push(monster)}
        else
          Monster.where('pairs LIKE ?', "%#{params[:keyword]}%").each {|monster| @monster.push(monster)}
        end
      end

    else
      if params[:search_regexp] == "完全一致検索"
        @monster.push(Monster.find_by(name: params[:keyword]))
      else
        if !params[:keyword].empty?
          Monster.where('name LIKE ?', "%#{params[:keyword]}%").each {|monster| @monster.push(monster)}
        end
      end

    end

    if @monster.compact.empty?
      @monster.compact!
      Monster.all.each {|monster| @monster.push(monster)}
    end

    render partial: 'detail', locals: { :monster => @monster}

  end

  private

    def url_terry
      "https://altema.jp/terrysp/haigouhyou"
    end

    def search_html(url)
      charset = nil
      search_url = URI.encode url
      html = open(search_url) do |f|
        charset = f.charset # 文字種別を取得
        f.read # htmlを読み込んで変数htmlに渡す
      end
      return html,charset
    end

    def get_info_terry(result)
      @outstr_terry = ""
      for i in 3..12 do
        for j in 1..100 do
          result.xpath("//div[1]/div[2]/div[1]/table[#{i}]/tbody/tr[#{j}]").each do |node|
            if node.css('a.mokujimusibtn').present? || node.css('a/span/img').present?
              @outstr_terry.chop!.chop!
              @outstr_terry = @outstr_terry + "};{" + "！" + node.xpath('td[1]/a/span').inner_text + "！:"
              if node.xpath('td[2]/a[2]').present?
                @outstr_terry = @outstr_terry + "（" + node.xpath('td[2]/a[1]').inner_text + "＋" + node.xpath('td[2]/a[2]').inner_text + "）or"
              else
                if node.xpath('td[2]').present?
                  @outstr_terry = @outstr_terry + "（" + node.xpath('td[2]').inner_text.gsub(/\s/,"＋") + "）or"
                else
                  @outstr_terry = @outstr_terry + "（" + node.xpath('td').inner_text.gsub(/\s/,"＋") + "）or"
                end
              end
            elsif
              @outstr_terry = @outstr_terry + "（" + node.xpath('td/a[1]').inner_text + "＋" + node.xpath('td/a[2]').inner_text + "）or"
            end

          end

        end
      end

      @outstr_terry.gsub(/（＋）/,"").sub(/};/,"").chop!.chop! + "}"

    end

    def register
      terry_text = File.read("app/assets/terry.txt") # get_info_terryで出力したデータに少し手を加えたもの
      terry_text.split(/;/).each do |info|
        Regexp.new(/.*！(.*)！.*/) =~ info
        name = $~.captures[0] #name
        tmpstr = $~.captures[0]
        count = terry_text.scan("（" + tmpstr + "＋").length + terry_text.scan("＋" + tmpstr + "）" ).length # count
        Regexp.new(/.*:(.*)}$/) =~ info
        pairs = $~.captures[0].gsub(/or/, "\n").gsub(/（|）/, "") # pairs
        monster = Monster.create(name: name, pairs: pairs, count: count)
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @monster = []
    @history = []
    current_user
    read_history
  end

  def create
    user = User.find_by(name: params[:name])
    if user
      log_in user
      current_user

      redirect_to '/sessions/new'
    else

      redirect_to :root, danger:'登録されていないユーザーです'
    end
  end

  def destroy
    log_out
    redirect_to :root
  end

  def search
    @search = []
    @monster = []
    @history = []

    current_user

    if params[:search_status] == "true"
      if !params[:keyword].empty?
        if params[:search_regexp] == "完全一致検索"
          Monster.where('pairs LIKE ?', "%＋#{params[:keyword]}").each {|search| @search.push(search)}
          Monster.where('pairs LIKE ?', "#{params[:keyword]}＋%").each {|search| @search.push(search)}
        else
          Monster.where('pairs LIKE ?', "%#{params[:keyword]}%").each {|search| @search.push(search)}
        end
      end

    else
      if params[:search_regexp] == "完全一致検索"
        @search.push(Monster.find_by(name: params[:keyword]))
      else
        if !params[:keyword].empty?
          Monster.where('name LIKE ?', "%#{params[:keyword]}%").each {|search| @search.push(search)}
        end
      end
    end

    if !@search.compact.empty?
      regist_history
    end

    @history = []
    read_history

    render partial: 'detail', locals: { :monster => @monster} and return

  end

  def delete
    if !params[:delete_histories].nil?
      current_user
      @history = History.where(user_name: "#{@current_user_name}")
      delete_history
    end

    redirect_to '/sessions/new'
  end

  private
    def log_in(user)
      session[:user_id] = user.id
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
      @current_user_name = nil
    end

    def regist_history
      @search.each do |mons|
        @history = @current_user.histories.new(user_name: @current_user_name ,monster_name: mons[:name])
        @history.save!
      end
    end

    def read_history
      @history = History.where(user_name: "#{@current_user_name}")

      if !@history.nil?
        @history.each do |history|
          @monster.unshift(Monster.find_by(name: history[:monster_name]))
        end
      end
    end

    def delete_history
      params[:delete_histories].each do |delete_num|
        History.find(@history[@history.length - delete_num.to_i][:id]).destroy
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(name: params[:user][:name])
    if user.save
      @monster = Monster.all
      redirect_to :root, layout: "application.html.erb", success: '登録が完了しました'
    else
      redirect_to new_user_url, danger:'登録済みの名前または空白です'
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StSuppo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <%= yield %>

    <script>
      $(function(){
        $(".alert").fadeOut(3000);
      });
    </script>
  </body>
</html>

app/views/pages/_detail.html.erb
<table class="monster_table_default">
  <tr class="monster_table_header">
    <th class="monster_table_header_name">モンスター名</th>
    <th class="monster_table_header_pairs">配合元（両親）</th>
    <th class="monster_table_header_count">両親となる回数</th>
  </tr>
  <% @monster.each do |monster| %>
  <tr class="monster_table_detail">
    <td class="monster_table_name"><%= monster.name %></td>
    <td class="monster_table_pairs"><%= simple_format(monster.pairs) %></td>
    <td class="monster_table_count"><%= monster.count %></td>
  </tr>
  <% end %>
</table>

app/views/pages/index.html.erb
<div class="main">
  <div class="title">テリワンSPモンスター配合表</div>

  <div class="search_wrapper">
    <div class="search_status">
      <%= form_with method: :get, url: pages_search_path do |form| %>
      <div class="search_status_keyword_title"><%= form.label("検索モンスター") %></div>
        <div class="search_status_keyword">
          <%= form.text_field :keyword , class: 'keyword_text_field'%><br>
        </div>
        <div class="search_status_radio">
          <%= radio_button_tag :search_regexp, :完全一致検索 , {:checked => true}%>
          <%= label_tag("完全一致検索", '完全一致検索', class:"search_status_radio_label") %>
        </div>
        <div class="search_status_radio">
          <%= radio_button_tag :search_regexp, :あいまい検索 %>
          <%= label_tag("あいまい検索", 'あいまい検索', class:"search_status_radio_label") %>
        </div>
        <div class="search_status_check">
          <%= form.check_box :search_status ,{},checked_value = true ,unchecked_value = false %>
          <%= label_tag("配合元を検索", '配合元を検索', class:"search_status_check_label") %>
        </div>
        <div class="search_status_search_btn">
          <%= form.submit("検索する", class: "search_btn", data: { disable_with: '検索中...' } ) %>
        </div>
      <% end %>
    </div>
    <div class="search_login">
      <%= form_with method: :post, url: sessions_create_path do |f| %>
        <div class="search_login_name">
          <%= f.label :name, class: 'search_login_name_text' %>
          <%= f.text_field :name, class: 'search_login_name_text' %>
        </div>
        <%= f.submit "ログイン", class: 'search_login_btn' %>
      <% end %>
      <div class="user_regist">
        <%= link_to 'ユーザー新規登録', 'users/new', class: 'user_regist_link' %>
      </div>
    </div>
  </div>
  <div class="result_wrapper">
    <div id="updated_by_ajax" class="monster_table">
    <table class="monster_table_default">
      <tr class="monster_table_header">
        <th class="monster_table_header_name">モンスター名</th>
        <th class="monster_table_header_pairs">配合元（両親）</th>
        <th class="monster_table_header_count">両親と　なる回数</th>
      </tr>
      <% @monster.each do |monster| %>
      <tr class="monster_table_detail">
        <td class="monster_table_name"><%= monster.name %></td>
        <td class="monster_table_pairs"><%= simple_format(monster.pairs) %></td>
        <td class="monster_table_count"><%= monster.count %></td>
      </tr>
      <% end %>
    </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main">
  <div class="user">
    <%= form_with(model: @user) do |form| %>
      <div class="user_name">
        <%= form.label :name, class: 'user_name_text' %>
        <%= form.text_field :name, class: 'user_name_field' %>
      </div>
      <%= form.submit "新規登録", class: 'user_btn' %>
    <% end %>
  </div>
</div>